# 一个yml文件就是一个workflow，定义什么时候触发，什么时候跑哪些job
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # Job 1: Lint（代码风格检查）
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      - run: pip install ruff
      - run: ruff check .
      - run: ruff format --check .

  # Job 2: Test（运行测试）
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
#     这里是添加了缓存
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip           # pip 下载缓存目录
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}  # 用 requirements.txt 的哈希做 key
          restore-keys: | 
            ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt
      - run: pytest --tb=short

  # Job 3: Build（构建产物）—— 依赖 lint 和 test 都通过
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: pip install build
      - run: python -m build
