# 一个yml文件就是一个workflow，定义什么时候触发，什么时候跑哪些job
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # Job 1: Lint（代码风格检查）
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-env
        with:
          python-version: ${{ matrix.python-version }}
          install-cmd: "pip install ruff"
      - run: ruff check .
      - run: ruff format --check .

  # Job 2: Test（运行测试）
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-env
      - run: pytest --tb=short

  # Job 3: Build（构建产物）—— 依赖 lint 和 test 都通过
  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-env
        with:
          install-cmd: "pip install build"
      - run: python -m build
